name: PiggyCrates
main: DaPigGuy\PiggyCrates\PiggyCrates
version: 4.0.0
api: 4.9.9 #bump version 5.0 it works :D
load: POSTWORLD
author: DaPigGuy/NemesisFire2348 aka DragonfireHD98
softdepend: ["PiggyCustomEnchants"]
website: "https://github.com/DaPigGuy/PiggyCrates/"
website: "https://discord.gg/66j9cFm6Cc"
permissions:
  piggycrates:
    default: false
    description: "Allows usage of all PiggyCrates features"
  piggycrates.command:
    default: op
    description: "Allow usage of all PiggyCrates commands"
  piggycrates.command.crate:
    default: op
    description: "Allow usage of the /crate command"
  piggycrates.command.key:
    default: op
    description: "Allow usage of the /key command"
  piggycrates.command.keyall:
    default: op
    description: "Allow usage of the /keyall command"
